# *NUMPY**
* NumPy, which stands for Numerical Python, is a fundamental library in Python used for numerical and mathematical operations. It provides support for working with arrays, matrices, and a wide range of mathematical functions to perform computations efficiently.
* uses same data types of elements
* faster than list ,tuple

In [ ]:
# install numpy array
! pip install numpy

In [ ]:
# import numpy
import numpy as np

**1. create numpy array ?**

In [ ]:
# np.array()


arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
# using list
l=['a','b','c']
arr1=np.array(l)
print(arr1)
print(type(arr1))

['a' 'b' 'c']
<class 'numpy.ndarray'>


In [ ]:
# using tuple
t=(True,False)
arr2=np.array(t)
print(arr2)
print(type(arr2))

[ True False]
<class 'numpy.ndarray'>


In [ ]:
# mixed data types add ?
l1=('text',1,2,3)

arr3=np.array(l1)
print(arr3)  # The integers have been converted to strings in order to maintain a uniform data type.

['text' '1' '2' '3']


In [ ]:
# arange ()


# Creating an array with a range of values
my_range_array = np.arange(0, 10, 2) # Start at 0, stop before 10, step by 2

print(my_range_array)
print(type( my_range_array))

[0 2 4 6 8]
<class 'numpy.ndarray'>


# 2.**DIMENSIONS IN ARRAY**

In [ ]:
# 0- DIMENSION ARRAY
a=np.array(20)
print(type(a))
print("array is ",a)
print("dimensions of array a is",a.ndim)

<class 'numpy.ndarray'>
array is  20
dimensions of array a is 0


***array.ndim:return dimensions of an array***

In [ ]:
a=np.array([1,2,3,4,5])

print("dimensions",a.ndim)
print(a)

dimensions 1
[1 2 3 4 5]


In [ ]:
b=np.array((1,2,3,45))
print(b.ndim)

1


In [ ]:
# size of an array : total elemnts
print("size of an array a ",a.size)
print("size of an array b ",b.size)

size of an array a  5
size of an array b  4


In [ ]:
# check data type of an array ?array.dtype: return data type of inside elelments in array
# type(): return types of an array

print("data type of an array elements ",a.dtype)
print("type of an array ",type(a))

data type of an array elements  int64
type of an array  <class 'numpy.ndarray'>


In [ ]:
# shape of array : no .of elemnets in each dimension
print("shape of an array ",a.shape )

shape of an array  (5,)


In [ ]:
b.shape

(4,)

**- arr.ndim tells you how many dimensions the array has.
- arr.shape gives you the dimensions of the array in the form of a tuple.bold text**

## 2d array:

In [ ]:
# create 2 d array : matrix

c=np.array([[1,2,3],[4,5,6]])
print("array is",c)
print("dimensions of an array",c.ndim)
print("size of an array",c.size)
print("shape of an array",c.shape)
print("type of an array c",type(c))
print("data type of array elements ", c.dtype)

#arr.ndim tells you how many dimensions the array has.
# arr.shape gives you the dimensions of the array in the form of a tuple.(rows,columns)

array is [[1 2 3]
 [4 5 6]]
dimensions of an array 2
size of an array 6
shape of an array (2, 3)
type of an array c <class 'numpy.ndarray'>
data type of array elements  int64


## 3d array:

In [ ]:
# create an 3 d array ?

d=np.array([[[1,2,3,4],[4,5,6,8],[8,92,0,1]]])

d

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  8],
        [ 8, 92,  0,  1]]])

In [ ]:
print("array is",d)
print("dimensions of an array",d.ndim)
print("size of an array",d.size)
print("shape of an array",d.shape)
print("type of an array c",type(d))
print("data type of array elements ", d.dtype)


array is [[[ 1  2  3  4]
  [ 4  5  6  8]
  [ 8 92  0  1]]]
dimensions of an array 3
size of an array 12
shape of an array (1, 3, 4)
type of an array c <class 'numpy.ndarray'>
data type of array elements  int64


##4d array:

In [ ]:
E=np.array([[[[1,2,3],[4,5,6]]]])
E

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [ ]:
print("array is",E)
print("dimensions of an array",E.ndim)
print("size of an array",E.size)
print("shape of an array",E.shape)
print("type of an array c",type(E))
print("data type of array elements ", E.dtype)


array is [[[[1 2 3]
   [4 5 6]]]]
dimensions of an array 4
size of an array 6
shape of an array (1, 1, 2, 3)
type of an array c <class 'numpy.ndarray'>
data type of array elements  int64


## HIGHER DIMENSIONAL ARRAY:

# **3. Create an array with definde data type**

In [ ]:
# float array
arr=np.array([1,2,3,4,5],dtype='f')
print(arr)
print(type(arr))
print("data tye of elements ",arr.dtype)


[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
data tye of elements  float32


In [ ]:
arr.astype("float32")
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
# int array
arr2=np.array([1.2,2.1,3,4,5],dtype='i')
print(arr2)
print(type(arr2))
print("data tye of elements ",arr2.dtype)




[1 2 3 4 5]
<class 'numpy.ndarray'>
data tye of elements  int32


In [ ]:
arr2.astype("float32")# convert into float again

array([1., 2., 3., 4., 5.], dtype=float32)

# **5.Type casting in numpy array**

In [ ]:
#float to int :

arr3=np.array([1.2,2.3,3.5,4])
print(arr3)
#convert into int
arr4= arr3.astype('i')
print(arr4)

[1.2 2.3 3.5 4. ]
[1 2 3 4]


In [ ]:
#int to float

arr5=np.array([1,2,3,3,4])
print(arr5)
#convert into int
newarr5= arr4.astype('f')
print(newarr5)

[1 2 3 3 4]
[1.2 2.3 3.5 4. ]


In [ ]:
a=arr4.astype(float) # 'f or type only float

print(a)

[1.2 2.3 3.5 4. ]


In [ ]:
#int to boolean

arr_int = np.array([0, 1, 2, 3, 0])

# Type casting to boolean
arr_bool = arr_int.astype(bool)

print(arr_bool)


[False  True  True  True False]


In [ ]:
# int to string :
arr_int = np.array([1, 2, 3, 4])

# Type casting to string
arr_str = arr_int.astype(str)

print(arr_str)

['1' '2' '3' '4']


# **5. BUILT IN METHODS/FUNCTIONS TO CREATE AN ARRAYS**

* arange: return evenly spaced values withing given interval (start,stop,step)
- linspace():return evenly spaced values withing given interval (start,stop,step)
- full():
-eye():
- ones():
- zeros():

*range() is a built-in Python function primarily used for creating loops, numpy.arange() is a NumPy function that provides more flexibility for generating numerical sequences as NumPy arrays.*

In [ ]:
# using arange()
a=np.arange(0,10) # 0 to 9
print(a)
print(type(a))
print("dataty of elements",a.dtype)


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
dataty of elements int64


In [ ]:
a=np.arange(0,10,1) # 0 to 9
print(a)
print(type(a))
print("dataty of elements",a.dtype)


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
dataty of elements int64


In [ ]:
a2=np.arange(11)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.arange(0,10,2) # 0 to 9
print(a)
print(type(a))
print("dataty of elements",a.dtype)

[0 2 4 6 8]
<class 'numpy.ndarray'>
dataty of elements int64


In [ ]:
# using range() python in buil function mostly used in for loop
c=range(1,3)
print(c)
print(type(c))

range(1, 3)
<class 'range'>


In [ ]:
#
np.arange(13) # 0 to 12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#1 to 12
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# odd no.array  :
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
# even no. array :
np.arange(2,13,2)

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
#linspace(): return evenly spaced numbers

z=np.linspace() #required 2 arguments
z

TypeError: ignored

In [ ]:
z=np.linspace(1,5) #1 to 5 equally step 1to 5
z

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
z=np.linspace(1,5,3) # 1 t0 5 3 elements
z

array([1., 3., 5.])

In [ ]:
z=np.linspace(1,5,3,retstep=True) # 1 t0 5 3 elements  #gives step size 2 .0
z

(array([1., 3., 5.]), 2.0)

In [ ]:
np.linspace(1,100,5) # generate 5 elements 12 to 100 using linspace()

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
np.linspace(1,100,5,retstep=True) # generate 5 elements 12 to 100 using linspace() and retstep steps is 24.75


(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

**np.ones()**
- it retuns one values

In [ ]:
a=np.ones(3) # by default generates float array
a # 3 ones

array([1., 1., 1.])

In [ ]:
print(a.shape)
print(a.dtype)
print(a.ndim)

(3,)
float64
1


In [ ]:
a=np.ones(3,dtype='i') # by default generates float array
a # 3 ones

array([1, 1, 1], dtype=int32)

In [ ]:
b=np.ones((2,2)) # 2 rows 2 columns 2d matrix
print(b)
print(b.shape)
print(b.dtype)
print(b.ndim)

[[1. 1.]
 [1. 1.]]
(2, 2)
float64
2


In [ ]:
b=np.ones((2,3)) # 2 rows 2 columns 2d matrix
print(b)
print(b.shape)
print(b.dtype)
print(b.ndim)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
float64
2


In [ ]:
# 3 d ones array
z=np.ones((1,3,3))
print(z)
print(z.ndim)
print(z.shape)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3
(1, 3, 3)


In [ ]:
z=np.ones((2,2,3)) # 2 ELEMTS 2 ROWS ,3 COLUMNS
print(z)
print(z.ndim)
print(z.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
3
(2, 2, 3)


In [ ]:
z=np.ones((2,2,3),dtype='i') # 2 ELEMTS 2 ROWS ,3 COLUMNS
print(z)
print(z.ndim)
print(z.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
3
(2, 2, 3)


**zeros()- return zero elements array**

In [ ]:
s=np.zeros(2) # 1d 2 zeros
print(s)
print(s.ndim)
print(s.shape)
print(s.dtype)

[0. 0.]
1
(2,)
float64


In [ ]:
s=np.zeros(3,dtype='i') # 1d 3 zeros
print(s)
print(s.ndim)
print(s.shape)
print(s.dtype)


[0 0 0]
1
(3,)
int32


In [ ]:
a=np.zeros((2,2)) # 2d 2*2
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)


[[0. 0.]
 [0. 0.]]
2
(2, 2)
float64


In [ ]:
a=np.zeros((2,2,3)) # 3d
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
3
(2, 2, 3)
float64


**eye():**
- return identity matrix

In [ ]:
e=np.eye(2) # 2d
print(e)
print(type(e))
print(e.dtype)
print(e.ndim)
print(e.shape)

[[1. 0.]
 [0. 1.]]
<class 'numpy.ndarray'>
float64
2
(2, 2)


In [ ]:
e=np.eye(1) # 2d
print(e)
print(type(e))
print(e.dtype)
print(e.ndim)
print(e.shape)

[[1.]]
<class 'numpy.ndarray'>
float64
2
(1, 1)


In [ ]:
e=np.eye(3,3) # 2d
print(e)
print(type(e))
print(e.dtype)
print(e.ndim)
print(e.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
float64
2
(3, 3)


**full()**
- return same elements

In [ ]:
s=np.full((2,2),4) # 2d 2rows 2 columns of 4 elements
print(s)
print(s.ndim)

[[4 4]
 [4 4]]
2


In [ ]:
s=np.full((2,2),-3) # 2d 2rows 2 columns of 4 elements
print(s)
print(s.ndim)

[[-3 -3]
 [-3 -3]]
2


In [ ]:
s=np.full((3,2),4) # 2d 3rows 2 columns of 4 all elements
print(s)
print(s.ndim)

[[4 4]
 [4 4]
 [4 4]]
2


In [ ]:
s=np.full((2),4) # 1d
print(s)
print(s.ndim)

[4 4]
1


In [ ]:
s=np.full((3),5) # 1d 5 occurs 3 times
print(s)
print(s.ndim)

[5 5 5]
1


In [ ]:
s=np.full(5,(3)) # 1d ,3 occurs 5 times
print(s)
print(s.ndim)

[3 3 3 3 3]
1


# **7.Reshape of an array**
- change dimensions

In [ ]:
ar=np.array([1,2,3,4,5,6])
print(ar)
print(ar.ndim)

[1 2 3 4 5 6]
1


In [ ]:
ar1=ar.reshape(3,2) # 1d to 2d
print(ar1)
print(ar1.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
# 1d to 3d
ar2=np.array([1,2,3,5,6,7])
print(ar2)
print(ar2.ndim)
ar3=ar2.reshape(2,3,1)
print(ar3)
print(ar3.ndim)


[1 2 3 5 6 7]
1
[[[1]
  [2]
  [3]]

 [[5]
  [6]
  [7]]]
3


In [ ]:
# 1d to 3d
a=np.arange(1,13)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [ ]:
a2=a.reshape(1,4,3)
print(a2)
print(a2.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3


In [ ]:
a2=a.reshape(2,2,3)
print(a2)
print(a2.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [ ]:
# create 1 to 17 elements of 3d array with 2 layers

d=np.arange(1,17)
print(d)
print(d.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [ ]:
a3=d.reshape(2,4,2)
print(a3)
print(a3.ndim)
print(a3.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
3
16


In [ ]:
d=np.arange(1,19)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
a3=d.reshape(3,3,2)
print(a3)
print(a3.ndim)
print(a3.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
3
18


# **Create an array using np.rand(),randn(),randint()**

*np.rand()*
- uniform drandom distribution 0 to 1

In [ ]:
import random
ar=np.random.rand(4) # 4 elements 0 to 1
print(ar)

[0.35921658 0.78195835 0.88907124 0.17320048]


In [ ]:
np.random.rand(3,2) # 2d

array([[0.49493397, 0.21304659],
       [0.69163279, 0.91593951],
       [0.83186181, 0.87312779]])

**randn()**
- return standard normal distribution values
-values -3 to +3

In [ ]:
ar2=np.random.randn(3) # -3 to +3 ,3 elements
print(ar2)


[-0.73965397 -1.52697873  1.03064222]


In [ ]:
ar2=np.random.randn(5) # -3 to +3 ,5 elements
print(ar2)

[ 1.35131385 -0.65876079 -1.74953548  0.23513788 -1.55307198]


In [ ]:
ar3=np.random.randn(3,3)# 2d
print(ar3)

[[ 0.29115208  1.02615467  0.36139719]
 [ 0.3064449  -1.15041692 -1.45311615]
 [-0.28975254  1.11404342 -1.08454562]]


**randint()**
- return integer values

In [ ]:
ari=np.random.randint(10)
print(ari)

5


In [ ]:
ari=np.random.randint(3,5)
print(ari)

3


In [ ]:
ari=np.random.randint(3,10,5)
print(ari)

[4 4 9 5 3]


In [ ]:
a=np.random.randint(1,100,20) # generate 1 t0 99 total 20 values
print(a)

[87  3 12 68 64 37 42 20  5 53 81 82 72 66 37 69 43 52 20 20]


In [ ]:
a=np.random.randint(1,50,10) # generate 1 t0 49 total 10 values
print(a)

[44 39 34 47 17 34 44  2 12 18]


**rand generates random numbers from a uniform distribution between 0 and 1.**
- randn generates random numbers from a standard normal distribution.
- randint generates random integers within a specified range

# **8.NUMPY OPERATIONS**
- ADDITION
- SUBTRACTION
- MULTIPLICATION
-DIVISION
- POWER

In [ ]:
# addition: sum of two arrays :
a=np.array([1,2,3,5])
b=np.array([4,5,7,10])
print(a)
print(b)

[1 2 3 5]
[ 4  5  7 10]


In [ ]:
a+b # element wise adding


array([ 5,  7, 10, 15])

In [ ]:
#subtraction
a-b

array([-3, -3, -4, -5])

In [ ]:
b-a

array([3, 3, 4, 5])

In [ ]:
#mul
a*b

array([ 4, 10, 21, 50])

In [ ]:
#scalar multplication
a*2

array([ 2,  4,  6, 10])

In [ ]:
#division
b/a

array([4.        , 2.5       , 2.33333333, 2.        ])

In [ ]:
#scaler division
a/2

array([0.5, 1. , 1.5, 2.5])

In [ ]:
# power :sqaure each elements
a=np.array([1,2,3])
a**2


array([1, 4, 9])

In [ ]:
#cube
a**3

array([ 1,  8, 27])

In [ ]:
# operations on 2d

import numpy as np
ar1=np.array([[8,2,3],[4,5,6]])
ar2=np.array([[2,2,6],[2,10,3]])
print(ar1)
print('\n',ar2)

[[8 2 3]
 [4 5 6]]

 [[ 2  2  6]
 [ 2 10  3]]


In [ ]:
ar1+ar2

array([[10,  4,  9],
       [ 6, 15,  9]])

In [ ]:
ar1-ar2

array([[ 6,  0, -3],
       [ 2, -5,  3]])

In [ ]:
ar1==ar2

array([[False,  True, False],
       [False, False, False]])

In [ ]:
ar1*ar2

array([[16,  4, 18],
       [ 8, 50, 18]])

In [ ]:
ar1/ar2

array([[4. , 1. , 0.5],
       [2. , 0.5, 2. ]])

In [ ]:
ar1*3

array([[24,  6,  9],
       [12, 15, 18]])

In [ ]:
# sqaure
ar1**2

array([[64,  4,  9],
       [16, 25, 36]])

# **10. Other numpy functions:**
- sqrt()
- exp()
-min()
-max()
- argmin()
-argmax()
- log
- sin()
-sort()

In [ ]:
#sqrt()

a=np.array((9,25,16))
a

array([ 9, 25, 16])

In [ ]:
np.sqrt(a)

array([3., 5., 4.])

In [ ]:
#exp()

np.exp(a)

array([8.10308393e+03, 7.20048993e+10, 8.88611052e+06])

In [ ]:
import random

In [ ]:
# max()np.min()

ar=np.random.randint(1,20,10)
print(ar)

[13 14  7  7 10  3 17 18 17  9]


In [ ]:
print(ar.min())
print(ar.max())

3
18


In [ ]:
print(np.min(ar))
print(np.max(ar))

3
18


In [ ]:
# ar.min() and ar.max() are methods of a NumPy array (ar). They directly operate on the array itself.
# np.min(ar) and np.max(ar) are functions from the NumPy library that can be used to find the minimum and maximum values of a NumPy array (

In [ ]:
#argmax(),argmin():
# argmin and argmax return the indices where these values occur.

ar

array([13, 14,  7,  7, 10,  3, 17, 18, 17,  9])

In [ ]:
print(np.max(ar)) # return max value from an array
print(np.argmax(ar)) # retun index of maximum value located
print(np.min(ar)) # retun mionimum values
print(np.argmin(ar)) # retun index of minimum value

18
7
3
5


In [ ]:
#np.log()
arr = np.array([1, 10, 100])
# The np.log() function calculates the natural logarithm (base e) of each element in the input array.
#It is useful for performing logarithmic calculations.

log_values = np.log(arr)
print(log_values)

[0.         2.30258509 4.60517019]


In [ ]:
# np.sin()
np.sin(arr)

array([ 0.84147098, -0.54402111, -0.50636564])