In [ ]:
# 1. python practice oct 23

In [ ]:
# fibbonai series :


## 2. find prime number :

In [ ]:
n= int(input())

for i in range (2,n):
  if n%i==0:
    print(n, "is not prime number")
    break
  else :
    (n, "it is prime number")

## 3.Palindrome ? or not ?


*This program checks if the input is the same when read forwards and backwards, ignoring spaces, commas, and periods*

In [ ]:
def is_palindrome(word):
    reversed_word = word[::-1]
    return word == reversed_word

# Get user input
word = input("Enter a word: ")

if is_palindrome(word):
    print(f"'{word}' is a palindrome")
else:
    print(f"'{word}' is not a palindrome")


KeyboardInterrupt: ignored

## 4.ANgram or not?


*if the sorted characters of both input strings are the same, which is a common way to determine if two strings are anagram*

In [ ]:
def check(s1,s2):
  if (sorted(s1)==sorted(s2)):
    print("the string are anagrams")
  else:
    print("the string are not anagram")

s1=input("enter s1 :")
s2=input("enters2 ")

check(s1,s2)

KeyboardInterrupt: ignored

## 5. FIND Armstrong number :
is a number that is equal to the sum of its own digits each raised to the power of the number of digits.
ex:
# num=153
sum = 1^3+5^3+3^3=1+125+27
 if (num== sum) is is Armstrong number :

In [ ]:
num=int(input())

sum=0
temp=num

while temp>0:   #153  #15 #1  # afterr 0 it take out of the loop
  digit=temp%10   #last digit=3   then #5 #1

  sum=sum+(digit**3)   # 27 stored insum
  temp=temp//10  # Gives remaing digits after using last #1  #0

if num==sum:
  print(num,"is An Armstrong number")

else:
  print(num,"is not Armstrong number")

## 6.check even or odd number ?

In [ ]:
x=int(input("enter a number:"))

if x%2==0:
  print(x,"even number")
else:
  print(x,"odd number")

enter a number:22
22 even number


In [ ]:
x=int(input("enter a number:"))

if x%2==0:
  print(x,"even number")
else:
  print(x,"odd number")

enter a number:127
127 odd number


## 7.add two numbers:?

In [ ]:
x1=int(input("enter 1st no."))
x2=int(input("enter 2nd no."))

x3=x1+x2
print(x3)

enter 1st no.1
enter 2nd no.2
3


##8.Print first 10 natural numbers?

* 1,2,3,4,5,6,7,8,9,10



In [ ]:
i=1

while i<=10:
  print(i,end=" ")
  i=i+1


1 2 3 4 5 6 7 8 9 10 

In [ ]:
#use for loop
for i in range(1,11):
  print(i,end=' ')


1 2 3 4 5 6 7 8 9 10 

In [ ]:
# third method
print([i for i in range(1,11)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


##9.Print 1st ten natural numbers in reverse manner ?

In [ ]:
#using while loop
i=10
while i>=1:
  print(i,end=' ')
  i=i-1



10 9 8 7 6 5 4 3 2 1 

In [ ]:
#or
i=1
while i<=10:
  print(11-i,end=' ')
  i=i+1

10 9 8 7 6 5 4 3 2 1 

In [ ]:
#using for loop :
for i in range(10,0,-1):
  print(i,end=' ')

10 9 8 7 6 5 4 3 2 1 

# # 10. Check leap year ? \n

leap year=366 days in a year

In [ ]:
y=int(input("enter year :"))

result="leap year" if y%400==0 else "Leap year" if y%4==0 and x%100 !=0 else "No leap year"
print(result)

KeyboardInterrupt: ignored

In [ ]:
y%400==0

##.Remove duplicates from a list of strings?

In [ ]:
names=["hhh","ggg",'123','123',123,"abc","ggg","HHH"]

u=list(set(names))
print(u)

['HHH', '123', 'hhh', 'ggg', 'abc', 123]


# ****Count Vowels and Consonants:

Remove Duplicates from a List:
Calculate BMI:
Calculate Euclidean Distance:
Calculate the Euclidean distance between two points in n-dimensional space.
Count Occurrences in a List:
String Reversal without Slicing:

## calculate sqaure root of given no.

In [ ]:
n=16
sq=n**(0.5)
print(sq)
type(sq)

4.0


float

**II Simple python Program:
**

## 1.  how to  list all keys from dictionary ?

In [ ]:
# 1. We use .key()function

In [ ]:
d={"DELHI":"NEW DELHI","MH":"MUMBAI","GOA":"Panji"} #dict

In [ ]:
d.keys() # .keys()

dict_keys(['DELHI', 'MH', 'GOA'])

In [ ]:
# Method 2: Using Dictionary Comprehension
def list_keys_method(dictionary):
    keys = [key for key in dictionary] #dict comprehensionn
    return keys

# Example Usage
sample_dict = {'apple': 1, 'banana': 2, 'cherry': 3}

keys_ = list_keys_method(sample_dict)
print(keys_)


['apple', 'banana', 'cherry']


**2. what is list comprehension in python with example ? *List comprehensions provide a concise way to create lists in Python.*

In [ ]:
# Example 1: Squares of numbers from 1 to 5
squares = [x**2 for x in range(1, 6)]

print(squares)
#[x**2 for x in range(1, 6)]: This is a list comprehension. It generates a new list by taking each element x from the range(1, 6) (which produces [1, 2, 3, 4, 5])
# and computes x**2 for each x.


[1, 4, 9, 16, 25]


In [ ]:
#EX 2: FIND EVEN NO >
# Generate a list of even numbers from 1 to 20
even_numbers = [x for x in range(1, 21) if x % 2 == 0]

print(even_numbers)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


**3. Find the sqaures of number using map()**

\n The map() function applies a specified function to all items in an input list and returns an iterator of the results.

In [ ]:
# a function to calculate the square
def square(x):
    return x**2


num = [1, 2, 3, 4, 5]

# Use map() to apply the square function to each element in the list
squares = list(map(square, num))


print(squares)


[1, 4, 9, 16, 25]


In [ ]:
def add(x):
  return x+x

num=[1,2,3]

add=list(map(add,num))
print(add)

[2, 4, 6]


**4.How to create datframe from a dict ?**

In [ ]:
import pandas as pd
d1 = {
    'Col1': ["abc", "cxz", "qwe", "axc"],
    'Col2': [10, 20, 30, 40] }

df=pd.DataFrame(d1)
df

Col1  Col2
0  abc    10
1  cxz    20
2  qwe    30
3  axc    40

In [ ]:
d2={"name":["axe","cxe"],
    "age":[21,22]
    }
df1=pd.DataFrame(d2)
df1

name  age
0  axe   21
1  cxe   22

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df1, *['age'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df1, *['name'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df1, *['age', 'count()', 'name'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df1, *['age'], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df1, *['age', 'name'], **{'inner': 'stick'})
chart

**5. How is list.append() is different from list.extend()?**

*\n list.append()- add the single  element at end of list one by one,the length of list increases by one*\n  *list.extend()- adds number of elements *

In [ ]:
l1=[1,2,4,5]
print(l1)

[1, 2, 4, 5]


In [ ]:
l1.append(1)
print(l1)

[1, 2, 4, 5, 1]


In [ ]:
l1.append([7,8,9])
#If the element itself is a list or any other iterable, it will be added as a single element, not as individual elements.
print(l1)

[1, 2, 4, 5, 1, [7, 8, 9]]


In [ ]:
#l.extend()
l=[1,3,6,8,9]

l.extend([1,2,4])  #dds multiple elements from an iterable.
print(l)

[1, 3, 6, 8, 9, 1, 2, 4]


**6.Creat 4*4 matrix and find the sum of all digonal elelements of matrix?**

In [ ]:
#use numpy and np.tace() or  .digonal()

import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 2, 12],
                   [13, 14, 15, 0]])
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  2 12]
 [13 14 15  0]]


In [ ]:
diag_sum=np.trace(matrix) #sum of diagonal elements
print(diag_sum)

9


In [ ]:
# or
m=np.arange(1,17).reshape(4,4)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(m.diagonal())

[ 1  6 11 16]


In [ ]:
print(m.diagonal().sum())

34


**7. remove duplicates elements from list?**

In [ ]:
#set()
my_list = [1, 1,2, 3, 2, 4, 3,3, 5, 1, 6, 7, 8, 5,"hh","hh",'g']
print(len(my_list))
# Use the set() function to remove duplicates, then convert it back to a list
unique_list = list(set(my_list))

print(unique_list)
print(len(unique_list))


17
[1, 2, 3, 4, 5, 6, 7, 8, 'g', 'hh']
10


# **TUPLE INTERVIEW Q AND A**

**1. HOW TO CREATE TUPLE IN PYTHON?**

In [ ]:
T=1,23,'A' #A tuple is an ordered, immutable collection of elements. It can store a sequence of items of different types, similar to a list.
print(T)
print(type(T))

(1, 23, 'A')
<class 'tuple'>


In [ ]:
# or we can for more readability:
my_tuple=(1,2,4,'a',6 ,"avc",'a',6)
print(my_tuple)
print(type(my_tuple))

(1, 2, 4, 'a', 6, 'avc', 'a', 6)
<class 'tuple'>


In [ ]:
#create empty tuple :
t1=()
type(t1)

tuple

*explain tuple unpacking.

Answer: Tuple unpacking is the process of extracting the individual elements of a tuple *

In [ ]:
my_tuple = (1, 2)
a, b = my_tuple
print(a,b)

1 2


In [ ]:
#calculate length of tuple :
t1=(1,2,3,41.2,5)
len(t1)


5

In [ ]:
#Acess elements using indexing
t1[2]

3

In [ ]:
#Concanate two tuples :
t1=(1,2,3)
t2=(4,5,6)
t3=t1+t2
print(t3)
print(type(t3))

(1, 2, 3, 4, 5, 6)
<class 'tuple'>


In [ ]:
#convert tuple into list :
t1=(1,2,3)
print(type(t1),"type pf t1 before converting ")

l=list(t1)
print("type of l after converting",l,type(l))

<class 'tuple'> type pf t1 before converting 
type of l after converting [1, 2, 3] <class 'list'>


In [ ]:
# find the maximum element in a tuple of integers.
my_tuple = (3, 7, 1, 9, 2)
max_element = max(my_tuple)
print(max_element)  # Output: 9


9


**2.find the index of a specific element in a tuple.**

In [ ]:
t=(1,2,4,6,'a',7)
#find specific index
t.index(1)


0

In [ ]:
t.index(6)

3

**3.Remove duplicate elements from tuple :**

In [ ]:
t=(1,2,33,4,33,55,6,66,7,8,92,2,3,4)

s=tuple(set(t))
print(s)

(1, 2, 33, 4, 66, 6, 7, 8, 3, 55, 92)


**4.to combine two tuples element-wise into a new tuple.**

In [ ]:
t1=1,2,3
t2=(4,2,5)
combinet=tuple(x+y for x,y in zip(t1,t2))
# zip function combines the elements of tuple1 and tuple2
print(combinet)

(5, 4, 8)


**5.calculate the dot product of two tuples**

In [ ]:
dot=tuple(x*y for x,y in zip(t1,t2))
print(dot,"dot product of two tuples")

(4, 4, 15) dot product of two tuples


**6.reverese a tuple**

In [ ]:
my_tup = (1, 2, 3, 4, 5)
reversed_tuple = my_tup[::-1]
print(reversed_tuple)  #

(5, 4, 3, 2, 1)


In [ ]:
my_t = (1, 2,'c', 3, 4, 5,'a')
reversed_tuple = my_t[::-1]
print(reversed_tuple)  #

('a', 5, 4, 3, 'c', 2, 1)


**7.sort a tuple of strings in alphabetical order**

In [ ]:
t=('bannana','apple','xyz','mango')
sorted(t)

['apple', 'bannana', 'mango', 'xyz']

 **8.Find common elements between two tuples:**

In [ ]:
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (4, 5, 6, 7, 8)
c= tuple(set(tuple1) & set(tuple2))
print("common elelents in tuples",c)

common elelents in tuples (4, 5)


**9. Remove a specific element from a tuple:**imp with function

In [ ]:
my_tuple = (1, 2, 3, 4, 5)

def remove_element(t, element):
    return tuple(x for x in t if x != element)



new_tuple = remove_element(my_tuple, 3)
print(new_tuple)  #


(1, 2, 4, 5)


**10. find the sum  even elements in a tuple:**

In [ ]:
 #find the sum of  even elements in a tuple:
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8)

def sum_even_elements(t):
    return sum(x for x in t if x % 2 == 0) #sum () is function


sum_even = sum_even_elements(my_tuple)
print(sum_even)


20


In [ ]:
 t2=(1, 2, 3, 4, 5, 6, 7, 8)

def sum_odd_elements(t):
    return sum(x for x in t if x % 2 != 0) #sum () is function


sum_odd = sum_odd_elements(t2)
print(sum_odd)


16


**11. count the frequency elemnets in tuple**

In [ ]:
tup = (1, 2, 2, 3, 3, 3, 4, 4, 4, 4)

tup.count(4)

4

In [ ]:
tup.count(3)

3

# **III SET INTERVIEW QUESTIONS ANS ANSWERS:**
\n The key characteristic of a set is that it contains unique elements, meaning no duplicate \n  set in Python is an unordered collection of unique elements. It is similar to a mathematical set and does not allow duplicate values. \n
Sets are useful when you want to store a collection of elements without duplicates, and you don't need to maintain the order of elements.

**1. CREATE SET ,CREATE EMPTY SET**

In [ ]:
#empty set
empty_set = set()
print(type(empty_set))
print(empty_set)

<class 'set'>
set()


In [ ]:
''' empty_set is an empty set. Keep in mind that you can't create an empty set using {} \n
because that syntax is used for creating an empty dictionary. '''

" empty_set is an empty set. Keep in mind that you can't create an empty set using {} \n\nbecause that syntax is used for creating an empty dictionary. "

In [ ]:
#create set :
s={1,2,4,3,2,4,6,7,7,5}
print(s)
type(s)

{1, 2, 3, 4, 5, 6, 7}


set

**2. What is a frozen set?** How is it different from a regular set?

A frozen set is an immutable version of a set. Once it's created, you cannot modify its elements. Regular sets are mutable and allow modification after creation.

In [ ]:
my_set = {1, 2, 3}
frozen_set = frozenset(my_set)
frozen_set


frozenset({1, 2, 3})

In [ ]:
print(type(frozen_set))

<class 'frozenset'>


**3.perform set operations like union, intersection, and difference in Python?**

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

In [ ]:
union_set = set1.union(set2)  # Union: {1, 2, 3, 4, 5} #TALE ALL elements except remove duplicates
intersection_set = set1.intersection(set2)  # Intersection: {3} #take common elements
diff_set = set1 - set2  # Difference: {1, 2} #  elements that are in set1 but not in set2.

print("UNION SET",union_set)
print("intersection set",intersection_set)
print("differences s1-s2 ", diff_set)


UNION SET {1, 2, 3, 4, 5}
intersection set {3}
differences s1-s2  {1, 2}


In [ ]:
#set2-set1 # contain set2 elements but not from set1
set2-set1
#This set contains elements that are unique to set2 and are not present in set1.

{4, 5}

**4.a program to create a set of unique integers:**

In [ ]:
n=[1,2,2,3,3,4,4,5,5,6,7,8,9,9,'a','a']

set(n)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 'a'}

In [ ]:
n={1,4,5,2} #unodered
print(n)

{1, 2, 4, 5}


**5.symmetric difference of two sets**

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

set1.symmetric_difference(set2)

{1, 2, 3, 6, 7, 8}

In [ ]:
#or
symmetric_difference = set1 ^ set2 #  also use
print(symmetric_difference)

{1, 2, 3, 6, 7, 8}


In [ ]:
#symmetric difference of set :minus common elements means
# The symmetric difference contains elements that are unique to either set1 or set2, but not in both.

**6. a program to check if a set is a subset of another set.**

In [ ]:
set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}
set1.issubset(set2)

True

In [ ]:
set2.issubset(set1)

False

**7. BUIT IN FUNCTION OF SET**

In [ ]:
#add(): Adds an element to the set.
s1={1,2,3,4,5}
s1.add(6)
print(s1)

{1, 2, 3, 4, 5, 6}


In [ ]:
#dds elements from another set (or any iterable) to the set.:update()
set1 = {1, 2, 3}
set2 = {3, 4, 5}
(set1.update(set2))
print(set1)



{1, 2, 3, 4, 5}


In [ ]:
#remove():
#Removes a specific element from the set. Raises a KeyError if the element is not present.
my_set = {1, 2, 3, 4}
my_set.remove(3)

In [ ]:
my_set

{1, 2, 4}

In [ ]:
#discard():Removes a specific element from the set (if it's present).
#Does not raise an error if the element is not present.
my_set.discard(3)

In [ ]:
my_set

{1, 2, 4}

In [ ]:
'''use discard()- if you want to handle the case where the element might not be present in the set, . \n
 se remove()- If you want to be sure the element is in the set before removing it, u'''

'use discard()- if you want to handle the case where the element might not be present in the set, . \n\n se remove()- If you want to be sure the element is in the set before removing it, u'

In [ ]:
#pop(): removces the arbitary elements from the set

s2={1,2,3,45,5,66,7,8}
print(s2.pop())

1


### Use pop():
When you want to remove and retrieve an arbitrary element from the set. This is often used when you want to process elements in a random order.
### Use remove():
When you want to remove a specific element and you're certain it exists in the set. If the element is not present, it raises an error.
### Use discard():
When you want to remove a specific element, but it's acceptable for the element not to be present in the set. **If the element is not present, no error is raised**.

In [ ]:
#clear():Removes all elements from the set, making it an empty set
my_s = {1, 2, 3, 4}
my_s.clear()
print(my_s)

set()


# **IV .DICTIONARY INTERVIEW Q& A**
* *A dictionary is an unordered collection of key-value pairs, where each key is unique. It is a mutable data structure that allows efficient retrieval of values based on their associated keys*

**1. How do you create an empty dictionary?**

In [ ]:
D={} #empty
print(type(D))

<class 'dict'>


**2. How do you add a key-value pair to a dictionary?**

In [ ]:
d={1:"ABC",2:"sxz",2:"asc",3:"qwe"} # only creae unique key value pair
print(d)

{1: 'ABC', 2: 'asc', 3: 'qwe'}


In [ ]:
type(d)

dict

In [ ]:
# 1. direct
my_dict = {}
my_dict['key'] = 'value'
print(my_dict)

{'key': 'value'}


In [ ]:
# 2.  Using a list of  Tuple
my_dict = {}
my_list = [('key1', 'value1'), ('key2', 'value2')]
my_dict.update(my_list)
print(my_dict)
# many ways we can create tuple of tuple ,list of list

{'key1': 'value1', 'key2': 'value2'}


**3. How to access dict elements**

In [ ]:
# Method 1: Using Square Brackets

d={1:"abc",2:"cde",3:"des",4:5}
print(d)

{1: 'abc', 2: 'cde', 3: 'des', 4: 5}


In [ ]:
d[2] # index at 2

'cde'

In [ ]:
d1={'A':"abc",'B':"cde",'C':"des",4:5}
print(d)


{'A': 'abc', 'B': 'cde', 'C': 'des', 4: 5}


In [ ]:
d1['B']

'cde'

In [ ]:
# Method 2: Using the get() Method

d1.get('A')   # my_dict.get('key1')

'abc'

In [ ]:
# 3. Using the pop() Method
d1.pop("A")

'abc'

In [ ]:
print(d1)

{'B': 'cde', 'C': 'des', 4: 5}


**4. How do you get a list of all keys in a dictionary?**

In [ ]:
d2={'a':123,'c':234, 'b':321,'q':789}
print(d2)
print(d2.keys()) # keys() access all keys

{'a': 123, 'c': 234, 'b': 321, 'q': 789}
dict_keys(['a', 'c', 'b', 'q'])


In [ ]:
d2={1:123,'4':234, '2':321,'7':789}
print(d2)
print(d2.keys())

{1: 123, '4': 234, '2': 321, '7': 789}
dict_keys([1, '4', '2', '7'])


**5.How do you get a list of all values in a dictionary?**

In [ ]:
d2={'a':123,'c':234, 'b':321,'q':789}
print(d2)
print(d2.keys(),"dict keys")  # acess all keys
values = list(d2.values()) # acess all values
print(values,"dict values ")

{'a': 123, 'c': 234, 'b': 321, 'q': 789}
dict_keys(['a', 'c', 'b', 'q']) dict keys
[123, 234, 321, 789] dict values 


**6.How do you iterate over the keys and values in a dictionary?**

In [ ]:
my_dict = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
for key, value in my_dict.items():
    print(f'Key: {key}, Value: {value}')


Key: key1, Value: value1
Key: key2, Value: value2
Key: key3, Value: value3


**7.How do you clear all elements from a dictionary?**

In [ ]:
my_dict.clear() # clear all data
print(my_dict)

{}


**8.How do you check if a value exists in a dictionary?**

In [ ]:
d={1:"abc",2:"xyz",3:"aqwe",5:"dfg"}
print(d)
print( "ghi"in d )

{1: 'abc', 2: 'xyz', 3: 'aqwe', 5: 'dfg'}
False


In [ ]:
print( "abc"in d.values()) # d.values( ) check uisng in operator values

True


In [ ]:
print(1 in d) # key exist or not

True


In [ ]:
print(7 in d)

False


In [ ]:
if 'xyz' in d.values():
    print('Value exists')

Value exists


**9. Find length of dict**

In [ ]:
len(d)

4

**10 How do you create a copy of a dictionary?**

In [ ]:
original_dict = {'a': 'value1', 'b': 'value2', 'd': 'value3'}
print("original_dict")
copied_dict = original_dict.copy()
print("copied dict",copied_dict)


original_dict
copied dict {'a': 'value1', 'b': 'value2', 'd': 'value3'}


**11. How do you get the value of a key with a default value if the key does not exist?**

In [ ]:
my_dict = {'key1': 'value1', 'key2': 'value2'}
value = my_dict.get('key3', 'default_value')
print(value)

default_value


**12. How do you sort a dictionary by its keys or values?**

In [ ]:
d3={2:"abc",3:"wer",5:"qwe",1:"dfr"}
print(d3)
sortd=dict(sorted(d3.items())) # d.items() # by key sorting is done
print("sorted dict",sortd)

{2: 'abc', 3: 'wer', 5: 'qwe', 1: 'dfr'}
sorted dict {1: 'dfr', 2: 'abc', 3: 'wer', 5: 'qwe'}


**13. How do you find the maximum and minimum value in a dictionary?**

In [ ]:
print(d3)
print(max(d3.values())) # values max
print(min(d3.values()))

{2: 'abc', 3: 'wer', 5: 'qwe', 1: 'dfr'}
wer
abc


In [ ]:
# or
my_dict = {'key1': 3, 'key2': 7, 'key3': 1}
max_value = max(my_dict.values())
min_value = min(my_dict.values())
print(max_value,min_value)

7 1


**14. How remove items from dict**
* del keyword :used to delete a specific key-value pair
* popitem(): The popitem() method is used to remove and return an arbitrary (random) key-value pair from the dictionary. If the dictionary is empty, it raises a KeyError
*pop() method is used to remove a specific key-value pair from the dictionary and return the value associated with that key. If the specified key is not present in the dictionary, it will raise a KeyError.
* clear() Method:sed to remove all key-value pairs from the dictionary, effectively emptying it.

In [ ]:
# 1. use del keyword:
d4={"a":123,"d":345,"c":567,"b":765}
print("original dict is",d4)
del d4['a'] # 1st no key pair deleted
print("after del keyword key value pair get deleted")
print(d4)


original dict is {'a': 123, 'd': 345, 'c': 567, 'b': 765}
after del keyword key value pair get deleted
{'d': 345, 'c': 567, 'b': 765}


In [ ]:
#2. pop()method

d5={3:"avc",2:"qwe"}
d5.pop(3) # using key pop that key value
print(d5)

{2: 'qwe'}


In [ ]:
# 3.popitem() :emove and return an arbitrary (random) key value pair
my_dict = {'a': 'value1', 'c': 'value2', 'b': 'value3'}

# Remove and return an arbitrary key-value pair
removed_item = my_dict.popitem()

print(my_dict, removed_item)


{'a': 'value1', 'c': 'value2'} ('b', 'value3')


In [ ]:
removed_item = my_dict.popitem()
print( removed_item)

('c', 'value2')


In [ ]:
# 4. using clear()
my_dict = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

# Remove all key-value pairs from the dictionary
my_dict.clear()


print(my_dict)


{}


# more practices refer more youtube videoes, my google colab pynb files